name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: niemandx
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --build-arg FLAG=${{ secrets.FLAG }} -t niemandx/flags-db:latest  .
          
      - name: Push Docker Image
        run: |
          docker push niemandx/flags-db:latest
      
